---
title: "NOAA-SEFSC Gulf of Mexico stock assessment improvement roadmap"
subtitle: "A reference page to plan and track research effort to improve stock assessment advice in the Gulf of Mexico"
page-layout: full
---

This website is intended to provide a living roadmap for planning and tracking research and development effort towards improving stock assessment methods and workflows in the Gulf of Mexico. This roadmap will maintain up to date records of ongoing and planned research in NOAA's Southeast Fisheries Science Center Gulf of Mexico sustainable fisheries branch with a particular focus on research efforts carried out under a 5 year RESTORE FFO 2023 Actionable Science grant awarded in collaboration with Vaughan Analytics <https://restoreactscienceprogram.noaa.gov/projects/building-next-generation-fishery-forecasting-capacity>. Providing details of ongoing and planned research is intended to facilitate collaboration opportunities with research efforts in other regions and agencies as promoted through NOAA's NMFS Open Science intiative <https://nmfs-opensci.github.io/>. Additionally this roadmap is intended to facilitate improved stakeholder and user awareness of ongoing research efforts and priorities and provide an avenue for feedback and discussion. 

### Disclaimer

This repository is a scientific product and is not official communication of the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. All NOAA GitHub project content is provided on an ‘as is’ basis and the user assumes responsibility for its use. Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.
