---
title: Background
---

## Initial Project Motivation 

Determining sustainable overfishing and acceptable biological catch limits (OFL’s & ABC’s) for annual fishery landings is one of the most important natural resource management decisions made in the Gulf of Mexico (Gulf). Annual OFL and ABC determinations must be made for all harvested species subject to a fishery management plan, as mandated by the Magnuson-Stevens Fishery Conservation and Management Act. These limits are intended to maximize the value of a fishery each year without harvesting so much that the future productivity of the fishery is diminished due to a depleted spawning stock biomass. 

In the Gulf, OFL’s are defined as the estimated landings with a fifty percent probability of being less than the maximum fishing rate that can sustain the target population biomass benchmark. ABC’s are a precautionary limit less than or equal to the OFL designed to account for scientific uncertainty in the OFL estimate. These limits are set based on the outputs of stock assessment models developed by fisheries scientists at NOAA’s Southeast Fisheries Science Center ([SEFSC](https://www.fisheries.noaa.gov/about/southeast-fisheries-science-center)) and the Florida Fish and Wildlife Conservation Commission ([FWC](https://myfwc.com/about/inside-fwc/fwri/)) which are reviewed and approved as suitable for management by the Scientific and Statistical Committee (SSC) of the Gulf of Mexico Fishery Management Council ([GMFMC](https://gulfcouncil.org/)). Successful fishery management in the Gulf is dependent upon stock assessment advice providing accurate OFL and ABC estimates. NOAA SEFSC catch limit monitoring [FAQ](https://www.fisheries.noaa.gov/southeast/sustainable-fisheries/frequent-questions-annual-catch-limit-monitoring) for additional details.


The stock assessment process used to define OFL and ABC limits broadly consists of two primary parts:

1.	A historic estimation period in which model parameter values are estimated based on an assumed model structure and the fit of the predicted model to observed data values.

2.	A projection period in which OFL and ABC fishing effort limits are estimated based on assumptions regarding future population and fishery conditions and sustainable stock status targets. 

Stock assessment methods have been continuously improved for over 100 years since the first fishery dynamic models were developed. Improvements in quantitative techniques and available computing power have led most research efforts to focus on the development and use of increasingly complex stock assessment modeling software models, such as [stock synthesis (SS)](https://github.com/nmfs-ost/ss3-source-code) used in the Gulf, for fisheries management. This has increased the capacity for stock assessment models to capture ever finer details of the fishery and population dynamics relevant to management. This is particularly important in Gulf fisheries, that often exhibit:

1.	Diverse commercial, for-hire, and recreational fishing fleets with distinct selectivity patterns, regional distributions, and priorities for what constitutes successful management outcomes (e.g., more fish or more days to fish). 

2.	Dynamic regulatory histories with a variety of catch/size/bag/trip limits and area/seasonal closures that vary through time and by fleet, region, and jurisdiction (federal vs state). 

3.	An inherently multi-species fishery where effort and selectivity towards one species may be significantly impacted by management decisions for other co-harvested species. 

However, no aspect of stock assessment modeling comes without trade offs. The narrow focus of historic research and development effort on increasing model complexity, and a strong reliance on model fit to historic data as a primary metric of model performance, has resulted in many challenges including: 

1.	Increased data processing and model development times, resulting in stock assessments being completed only once every 3-5 years for most species with a lag of 2-3 years between the last year of data in the model and the first year in which the results can be used for management. This delay reduces the accuracy of management advice and limits the ability of managers to make informed decisions in response to changes in the fishery, such as following or during a red tide bloom or cold snap. 

2.	The complexity of current stock assessments makes the results difficult to interpret, review, and diagnose for potential errors. Focusing model performance metrics on historic fits can also produce overfit models that are sensitive to new data inputs and produce volatile benchmark estimates from assessment to assessment. These limitations can hinder the incorporation of additional data sources such as environmental co-variates due to difficulty identifying the key processes they may be influencing. Volatile results can also lead to low trust in model results and subsequent regulatory action by stakeholders, reducing the effectiveness of management due to poor compliance. 

3.	The many decisions made when producing stock assessment projections have significant impacts on final stock status benchmarks and OFL/ABC estimates. These impacts are in general poorly understood and often overlooked in the decision-making process. The dearth of research into projection best practices, particularly in multi-fleet fisheries such as the Gulf, provides little guidance for managers tasked with making these decisions. This often leads to simple default choices being made that may not reflect true future conditions. This is particularly problematic when management advice is updated infrequently, which is currently the status quo for many stocks in the Gulf.   

This roadmap will track research efforts to develop new methods and technological capacity to increase the accuracy of projection assumptions, improve transparency in the impact of structural assumptions made in model development, and increase the throughput of stock assessment models to improve the accuracy of management advice under changing environmental conditions. These advancements will increase the accuracy and better capture the uncertainties of OFL and ABC estimates resulting in improved fishery management outcomes in the Gulf.

