---
title: "Interim Assessments"
---

## Why do we need them

  Determining sustainable overfishing limits and acceptable biological catch levels (catch limits) for annual fishery landings are some of the most important natural resource management decisions made that have large economic and social impacts. In the Gulf of Mexico (Gulf), long delays ([5+ years](https://sedarweb.org/sedar-assessments/)) are commonly observed between management updates due to stock assessment complexity, rulemaking timelines, and resource limitations. As a result, catch limits are generally set from short-term projections that assume average biological, ecological, and fishery conditions will prevail indefinitely. However, unpredictable events such as harmful algal blooms, hurricanes, and recruitment fluctuations combined with variability in realized fishery landings can result in a significant divergence of reality from these static assumptions. This can lead to significant overexploitation or underutilization of fisheries resources if not accounted for through timely updates of catch advice. To insure catch limits continue to achieve management objectives during the period between full assessments, interim assessments are used. Interim assessment is a broad term used to describe a variety of simplified approaches to updating catch limits that are intended to be responsive to changing conditions and fast to implement. These methods utilize deterministic rules or projections, similar to harvest control rules, to act on new data inputs without requiring the statistical parameter fitting of a new stock assessment.   
  

  
