---
title: Projections
---

## Uncertainty in short and long term recruitment trends and variability

One important need identified during scoping was an improvement in the handling of recruitment estimation and uncertainty in both the future projection period and the final years of the stock assessment model (late phase recruitments). Within the historic model period recruitment is modeled as following an empirical stock recruitment curve with annual random deviations. In the late phase period this stock recruitment curve or alternate methods such as a recent average can be used. These decisions can have large impacts on current stock status (overfishing and/or overfished determinations), benchmark, and OFL/ABC estimates. Accurately estimating current status and benchmarks in addition to OFL/ABC are aspects of fisheries management with critical importance to fishery stakeholders. Delayed identification of overfishing can compound its impact and increase the likelihood that the fishery may become overfished. Determining that a fishery is overfished can then require rebuilding plans and other accountability measures to be implemented. These measures inevitably impose large reductions in future landings through OFL/ABC reductions and can cause significant financial hardship for stakeholders. For this reason, improving the accuracy of management should always improve long term outcomes for stakeholders even in cases where short term yields are reduced. 
 
A range of candidate late phase recruitment methods will be simulation tested to identify an optimal method for incorporation into management best practices. Candidate approaches for implementing late phase recruitment include:

1.	Fixing recruitment at the mean estimate for recent years (current Gulf method).   

2.	Fixing recruitment at the stock recruitment curve estimate (current Gulf method).

3.	Fixing recruitment deviations at the mean estimate for recent years (new method).

4.	Using bootstrap resampling around the stock recruitment curve with variance estimated from the range of historic recruitment deviations (current South Atlantic method).

5.	Estimating recruitment using an artificial late phase recruitment index with mean and variance calculated the same as the South Atlantic method (new method).