---
title: Scalable models
---

## Overview

While maintaining sufficient stock assessment model complexity is critical to accurately determining management benchmarks and OFL/ABC limits, this complexity also increases the time required to develop, review and implement a stock assessment. The increasing complexity of stock assessments in the Gulf limits the throughput of both assessment advice and research and development by assessment scientists at SEFSC. The current throughput of 5+ years between assessments for many species hinders the ability of managers to identify and respond to changes in the fishery or identify the impact of model misspecification. Additionally, data are not incorporated into stock assessments until all sources are available for a given year. This results in a lag of 2-4 years between the last year of data informing the stock assessment and the first year for which management advice is provided. This combination of factors means that management actions such as OFL/ABC can at times be based upon data a decade or more old. To avoid this extreme scenario, alternative approaches are required that increase throughput and improve the quality of management decisions. Developing these approaches to rapidly inform fisheries management following a change can provide substantial value to stakeholders and reduce the risk of population depletion through overfishing. Current rapid methods applied in the Gulf, known as interim assessments, are limited to strictly updating recent landings data or scaling OFL/ABC limits based on changes in a single population abundance index. Neither of these methods re-estimate model parameters or quantify the potential impact re-estimation may have of OFL/ABC estimates. Being unable to incorporate other available data sources such as length and age compositions simultaneously also limits the utility of these methods, particularly in models where these data may be the most reliable information source. For example, an unexpected change in recruitment could be observable in composition data much sooner than an adult index. Incorporating these data and updating the recruitment expectation could remove large errors in outdated OFL/ABC estimates. 

This project will develop an improved interim assessment method, able to iteratively update data sources as they become available and selectively update parameter estimates as the data suggest they are needed. This approach is designed to combine the strengths and ameliorate the weaknesses of existing full stock assessment and interim assessment approaches. The proposed approach would implement the following procedure:

1.	First an initial full stock assessment base model would be developed for the species of interest, the same as a current stock assessment. This would provide foundational parameter estimates and diagnostics using years in which all data sources are available to prevent bias in the model estimates. The model interpretation methods developed in phase two of this project would be used in model development and to identify parameters of note that may require particular attention in interim update years.

2.	Using the base model, projections would be used to produce model estimated predictions of all data sources into future years. 

3.	As data sources become available for each new year, the model end year would be advanced to the most recent year with any data available and the new data added to the model. In order to avoid bias in the new results, the previous base model predictions would be added as observations for all sources not yet available. 

4.	As new data sources are added, the projections for later years are updated to account for the new observations. Model interpretation methods developed in phase 2 of this project will be applied to identify any significant deviations in parameter estimates suggested by new data sources.

5.	As feasible based on the time allotted to a given update, expert judgment or possible rules-based approaches could be used to identify which parameter values should be re-estimated for any given update. If no parameter estimates are updated the resulting advice can be considered closer to an interim-assessment. As more parameter estimates are updated to incorporate new data, the model outputs will more closely match a full assessment.

Using the diagnostic model interpretation method that will be developed earlier in this project will allow assessment scientists and GMFMC SSC reviewers to make informed judgements regarding when to update model parameter estimates as well as the expected impact this could have. Similar to previous phases above, this project will focus on developing software to implement this newly proposed interim assessment method and perform simulation testing to validate the performance improvement it provides over current interim-based assessment approaches. This phase will be completed over years 4 and 5 of the project with anticipated incorporation into management advice as early as 2028.    
